### ISSUE TITLE
Should show reason that protocol is disabled (if present)

### ISSUE THREAD

**Issue by iamthechad** [mgwalker/ssl-peeker#1]
I noticed that the output of this module simply shows "enabled" or "disabled" for protocols. This is not as informative as it could be, since the protocol could be disabled on the server side or simply not available on the client side. 

The response will contain an `error` property if the protocol could not be tested due to an issue on the client side.

```
{
        "protocol": "SSLv2_method",
        "name": "SSLv2",
        "enabled": false,
        "error": "The installed openssl library does not support \"SSLv2_method\""
}
```

The OpenSSL library may not support the protocol, and in NodeJS 4.0.0 and higher SSLv2 and SSLv3 are explicitly disabled, which is indicated by a different error message (in version `0.1.5` of `openssl`).

**Comment by mgwalker** [comment]
Good catch and good point.  I'll get an update out when I get home in a couple of days!

**Comment by mgwalker** [comment]
Actually, on further reflection, what I really want is to know whether the server has the protocol enabled regardless of client settings.  That might require a good bit more code, but it's the intended goal.  This issue is still good, though, and can serve as an interim solution.

**Comment by iamthechad** [comment]
I completely agree about wanting to know what the server has enabled. I'm going to see if there's anything else I can do in the `sslinfo` module, but between Node's disabling of SSLv2/v3 and disabled SSLv2 support in most versions of OpenSSL it may be difficult to get the full picture.

(Don't forget to update your dependency on `sslinfo`. Versions older than `0.1.5` break on NodeJS 4.0 and higher.)

**Comment by mgwalker** [comment]
Done.  I've got to get into a better habit of keeping my dependencies up to date!  Thanks!  :smile:
